Split
johnthagen/rust-belt pull request #130
Opened 2017-06-04 16:59 UTC by mcdenhoed

Implements #126, #127, #128

Asteroids split into smaller asteroids that take the shape of the original and spiral out.

2017-06-05 15:35 UTC, mcdenhoed commented
I've made it so it works with differing numbers of chunks. Setting it to 3 is very reasonable, though 2 has fun results too. Need to come up with a better way to add interior verts than just adding 0,0. Should also add more as that will make subsplits work better.

2017-06-05 16:08 UTC, mcdenhoed commented
I'm not sure about how to resolve the clippy error. I'm using the index in a for loop to access another array:
```rust
for i in 0..num_pieces {
            let mut new_shape =
            self.shape[indices[i]..indices[i+1] + 1].to_vec();
            ...
}
```
As you can see, I need to access two different indices. Not sure an idiomatic way to do that with a single iterator (don't doubt that there is one, just wasn't sure how).

2017-06-05 17:06 UTC, mcdenhoed commented
Hmm, zipping two copies of the index lists together might work. But that seems kind of ugly.

2017-06-05 17:18 UTC, bsvercl commented
Would it work to do this? 
```rust
for pair in indices.chunks(2).take(num_pieces) {
    let mut new_shape = self.shape[pair[0]..pair[1] + 1].to_vec();
...
```

2017-06-05 17:25 UTC, mcdenhoed commented
@bsvercl I think the issue with using `chunks(2)` is that, as described by the documentation for it:

> Returns an iterator over size elements of the slice at a time. **The chunks are slices and do not overlap**. If size does not divide the length of the slice, then the last chunk will not have length size.

The way I have the list generated right now, I need them to overlap (otherwise the resultant sub-asteroids have gaps between each-other).

However, zipping the list into itself, collecting, and THEN adding on the `0` and `len - 1` entries, followed by a use of `chunks(2)` just might do the trick. Might give that a shot. Thanks!

2017-06-05 19:53 UTC, mcdenhoed commented
As it turns out, `zip` creates an iterator with tuples of the zipped values, so with what I was talking about, there was no need to call `chunks` at all.

2017-06-05 20:16 UTC, johnthagen commented
@mcdenhoed If there was a legitimate false positive in clippy, might be a good idea to report to clippy.

2017-06-05 20:18 UTC, mcdenhoed commented
A clippy false positive seems hard to define to me, given that it's about code style and best practices

2017-06-05 20:24 UTC, johnthagen commented
This is really cool! 👍

2017-06-05 20:26 UTC, johnthagen commented on src/game/models/asteroid.rs
> +use game::models::{Collidable, Drawable, PI, PI_MULT_2, Positioned, Updateable};
Should we import this from `std::f64::consts` for clarity?

2017-06-05 20:26 UTC, johnthagen commented on src/game/models/mod.rs
> +    fn dx(&self) -> f64 {
Do you think we should rename this from `Positioned` now that we are modeling really a moving object? "`Movable`"?

2017-06-05 20:26 UTC, johnthagen commented on src/game/models/mod.rs
> +    fn dx(&self) -> f64 {
Also, is there any benefit to using [trait inheritance ](https://doc.rust-lang.org/book/traits.html#inheritance) to leave `Positioned` as a trait, but then have a derived trait for the "moving" types?

2017-06-05 20:31 UTC, johnthagen commented on src/game/models/asteroid.rs
> +        //let base_speed = self.vel();
Can remove dead code when ready to merge

2017-06-05 20:32 UTC, mcdenhoed commented on src/game/models/asteroid.rs
> +        //let base_speed = self.vel();
That's not dead though

2017-06-05 20:36 UTC, johnthagen commented on src/game/models/asteroid.rs
> +        //let base_speed = self.vel();
`//let base_speed = self.vel();` <- That? 😕

2017-06-05 20:37 UTC, mcdenhoed commented on src/game/models/asteroid.rs
> +        //let base_speed = self.vel();
Ohhh, it showed the previous method as being highlighted on mobile, haha. Didn't see the comment. Yeah, I can take that out.

2017-06-05 20:38 UTC, mcdenhoed commented on src/game/models/asteroid.rs
> +use game::models::{Collidable, Drawable, PI, PI_MULT_2, Positioned, Updateable};
Might as well. Same for PI_MULT_2?

2017-06-05 20:38 UTC, johnthagen commented on src/game/models/asteroid.rs
> +        //let base_speed = self.vel();
My understanding of Rust almost was blown.

2017-06-05 20:40 UTC, johnthagen commented on src/game/models/asteroid.rs
> +        let num_pieces = 3;
Adding a little bit of randomness to how it breaks up (`num_pieces`) could really make it look cool too. Maybe like a value between 2-5?

2017-06-05 20:41 UTC, mcdenhoed commented on src/game/models/mod.rs
> +    fn dx(&self) -> f64 {
That's a good idea. I'll read up about the inheritance. If we rename it to Kinetic, probably wouldn't need to inherit, right? So, the implementation that I have right now didn't end up using the gel stuff. Could even take it out for now.

2017-06-05 20:42 UTC, mcdenhoed commented on src/game/models/mod.rs
> +    fn dx(&self) -> f64 {
*vel . But might be able to make even better cracks with it.

2017-06-05 20:43 UTC, johnthagen commented on src/game/models/mod.rs
> +    fn dx(&self) -> f64 {
We'd only need to inherit if there are types that need to only `impl` the `Positioned` trait, but not all of the extra movement related `Kinetic` stuff like `dx`, `dy`, etc. I can't think of anything off hand.

2017-06-05 20:51 UTC, mcdenhoed commented on src/game/models/asteroid.rs
> +        let num_pieces = 3;
Yeah, I was going to do that in a later PR. 2-5 would work well. With a low number of vertices and a high number of chunks, the math for splitting them breaks down a bit, but 5 should still be fine.

2017-06-05 20:52 UTC, johnthagen commented on src/game/models/asteroid.rs
> +        let num_pieces = 3;
Doing it later is totally fine, and you're right probably a good idea so we have a commit we can refer back to that has the minimal work on it.

2017-06-05 20:54 UTC, johnthagen commented on src/game/models/asteroid.rs
> +use game::models::{Collidable, Drawable, PI, PI_MULT_2, Positioned, Updateable};
We had to define `PI_MULT_2` because `std` doesn't expose it, and [not every is onboard with "tau"](https://github.com/rust-lang/rfcs/issues/1486).

2017-06-05 20:57 UTC, mcdenhoed commented on src/game/models/asteroid.rs
> +use game::models::{Collidable, Drawable, PI, PI_MULT_2, Positioned, Updateable};
Ah, I forgot that PI_FRAC_2 was a thing but MULT wasn't

2017-06-05 21:05 UTC, mcdenhoed commented on src/game/models/asteroid.rs
> +        let num_pieces = 3;
We also should probably make the math use floats and cast to usize later to remove some of that rounding error.

2017-06-07 21:21 UTC, johnthagen commented
Reminder to remove the new Positioned methods if they are not used in this PR.

2017-06-07 23:19 UTC, mcdenhoed commented
@johnthagen Done.

2017-06-08 11:56 UTC, johnthagen requested changes
One minor fix, but otherwise big +1.

2017-06-08 11:56 UTC, johnthagen commented on src/game/models/asteroid.rs
> +        //let base_speed = self.vel();
@mcdenhoed Still to remove this line I think

2017-06-08 13:17 UTC, johnthagen approved these changes

2017-06-08 13:44 UTC, merged